# Generated by Django 6.0 on 2025-12-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentinteraction',
            name='conversation_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='agentinteraction',
            name='session_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='agentinteraction',
            name='response',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
